apiVersion: confluent.crossplane.io/v1alpha1
kind: SchemaRegistryCluster
metadata:
  annotations:
    meta.upbound.io/example-id: confluent/v1alpha1/schemaregistrycluster
  labels:
    testing.upbound.io/example-name: essentials
  name: essentials
spec:
  forProvider:
    environment:
    - id: ${confluent_environment.development.id}
    package: ${data.confluent_schema_registry_region.example.package}
    region:
    - id: ${data.confluent_schema_registry_region.example.id}

---

apiVersion: confluent.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: confluent/v1alpha1/schemaregistrycluster
  labels:
    testing.upbound.io/example-name: development
  name: development
spec:
  forProvider:
    displayName: Development
